### ISSUE TITLE
Electrical test gets really goofed up when there's a short to ground

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dougg3/mac-rom-simm-programmer#23]
```
It seems to think every pin is shorted to ground if any pin is shorted to 
ground. Just had this problem with an 8 MB SIMM. I would guess I have some 
logic wrong somewhere. Not sure if it's in the firmware or the programmer 
software at this point.
```

Original issue reported on code.google.com by `d...@schmorgal.com` on 4 Jul 2013 at 6:54

**Comment by dougg3** [comment]
This was fixed a while ago. In the firmware I had to keep track of which pins were shorted to ground, because they will show up as a short to every other pin while the other pins are being tested. That's because when the other pins are being tested, they are brought low, and then we test what others pins are low. The shorted to ground pin will be low during that test too.
